Repository kmarzi/project-2, pull requests merged in 2020-09, with the labels that each got.

#3 Models and Public folder update
  config/config.json
  fitLink.sql
  models/linkup.js
  models/user.js
  package-lock.json
  public/js/signup.js
  public/login.html
  public/signup.html
Labels: back end

#5 Models & Public
  models/user.js
  public/js/map.js
  public/js/viewEvents.js
  public/signup.html
  public/stylesheets/button.css
  public/stylesheets/style.css
  public/viewEvents.html
  public/welcome.html
Labels: front end

#7 Kim
  public/login.html
  public/signup.html
  public/stylesheets/images/basketball.jpeg
  public/stylesheets/images/bike2.jpeg
  public/stylesheets/images/p6.jpeg
  public/stylesheets/images/p7.jpeg
  public/stylesheets/images/p9.jpeg
  public/stylesheets/images/run.jpeg
  public/stylesheets/images/soccer.jpeg
  public/stylesheets/images/weight.jpeg
  public/stylesheets/images/white.jpeg
  public/stylesheets/images/yoga.jpeg
  public/stylesheets/style.css
  public/viewEvents.html
  public/welcome.html
Labels: front end

#8 added images folder
  public/stylesheets/style.css
  public/viewEvents.html
  public/welcome.html
Labels: front end

#14 View Events HTML update
  public/js/viewEvents.js
  public/viewEvents.html
Labels: front end

#20 View Events/ Create Events/ Seed CSV/ html & js
  models/linkup.js
  public/createEvents.html
  public/js/createLinkUp.js
  public/js/viewEvents.js
  public/viewEvents.html
  seed.csv
Labels: back end, front end

#31 profile modal retrieving by UserId
  public/createEvents.html
  public/js/profile.js
  public/js/viewEvents.js
  public/viewEvents.html
  routes/api-routes.js
Labels: back end, enhancement, front end
